### ISSUE TITLE
Add link to web page for download file in README 

### ISSUE THREAD

**Issue by malelew** [iremboldt/NonProfitsLNK#2]

**Comment by malelew** [comment]
https://www.irs.gov/charities-non-profits/form-990-series-downloads

**Comment by malelew** [comment]
I could also add a `main.py`where these files are downloaded

**Comment by iremboldt** [comment]
I added the links, and a main.py, but I'll have to mess around with actually ensuring that main.py works because I've never successfully done one of those before.
